### ISSUE TITLE
PowerToys Run clone of Need?

### ISSUE THREAD

**Issue by hlaueriksson** [Shinao/Wox.Plugins#3]
Hi!

This is a great project! ❤️ 
I was using your `Need` plugin for Wox back in the days.

I would like to write and publish a `Need` clone for [PowerToys Run](https://learn.microsoft.com/en-us/windows/powertoys/run).

Is it OK if I use the name `Need`?
And also mimic the behavior (How To Use) of the plugin?

Thanks!

/ Henrik

**Comment by Shinao** [comment]
Hey,

No problem, do whatever you want with it.

Cheers

**Comment by hlaueriksson** [comment]
Awesome, thanks!

**Comment by hlaueriksson** [comment]
Hi again @Shinao

I finally got around to release the Need plugin for PowerToys Run:

- https://github.com/hlaueriksson/Community.PowerToys.Run.Plugins#need

**Comment by Shinao** [comment]
Ooh, that looks nice, I will have to check that out and see if other plugins could also be used to improve productivity.
Thanks for letting me know @hlaueriksson

**Comment by hlaueriksson** [comment]
Unfortunately, the plugin manager in PowerToys Run does not offer support for finding or downloading community plugins.

So, I created an awesome list:

- https://github.com/hlaueriksson/awesome-powertoys-run-plugins

It contains some nice plugins for productivity.
